services:
  api:
    build:
      context: .
    # Pass environment variables
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    entrypoint: ["poetry", "run", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"

  app:
    build:
      context: .
    entrypoint: ["poetry", "run", "streamlit", "run", "src/app/main.py"]
    ports:
      - "8501:8501"
    depends_on:
      - api